spring:
  datasource:
    initialization-mode: always
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    #continueOnError: true
    username: sa
    password:
  h2.console.enabled: true
logging:
  level:
    root: info
server:
  port : 8084